/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import javax.swing.JLabel;
import com.formdev.flatlaf.FlatClientProperties;
import net.miginfocom.swing.MigLayout;
import raven.chart.pie.PieChart;



/**
 *
 * @author MY HP
 */
public class PieChartPanel extends javax.swing.JPanel {
  private PieChart pieChart1;
    private PieChart pieChart2;
    private PieChart pieChart3;
    private process_data.pieChart pieChart;
    public PieChartPanel() {
        initComponents();
        
        
        setLayout(new MigLayout("wrap 3")); // Sử dụng MigLayout để sắp xếp các thành phần vào 3 cột
        
        pieChart1 = createPieChart1("Top 5 sản phẩm/Dịch vụ bán được số lượng nhiều");
        add(pieChart1, "height 290");

        pieChart2 = createPieChart2("Top 5 Sản phẩm/ Dịch vụ có doanh thu cao");
        add(pieChart2, "height 290");

        pieChart3 = createPieChart3("Tỉ lệ nhập sản phẩm nhiều nhất");
        add(pieChart3, "height 290");
    }
    
    
    
    private PieChart createPieChart1(String headerText) {
                pieChart = new process_data.pieChart();
        PieChart chart1 = new PieChart();
        JLabel header = new JLabel(headerText);
        header.putClientProperty(FlatClientProperties.STYLE, "font:+1");
        chart1.setHeader(header);
        chart1.getChartColor().addColor(Color.decode("#f87171"), Color.decode("#fb923c"), Color.decode("#fbbf24"), Color.decode("#a3e635"), Color.decode("#34d399"), Color.decode("#22d3ee"), Color.decode("#818cf8"), Color.decode("#c084fc"));
        chart1.putClientProperty(FlatClientProperties.STYLE, "border:5,5,5,5,$Component.borderColor,,20");
        chart1.setDataset(pieChart.DataPieChart1());
        return chart1;
    }
 private PieChart createPieChart2(String headerText) {
                pieChart = new process_data.pieChart();
        PieChart chart1 = new PieChart();
        JLabel header = new JLabel(headerText);
        header.putClientProperty(FlatClientProperties.STYLE, "font:+1");
        chart1.setHeader(header);
        chart1.getChartColor().addColor(Color.decode("#f87171"), Color.decode("#fb923c"), Color.decode("#fbbf24"), Color.decode("#a3e635"), Color.decode("#34d399"), Color.decode("#22d3ee"), Color.decode("#818cf8"), Color.decode("#c084fc"));
        chart1.putClientProperty(FlatClientProperties.STYLE, "border:5,5,5,5,$Component.borderColor,,20");
        chart1.setDataset(pieChart.DataPieChart2());
        return chart1;
    }
  private PieChart createPieChart3(String headerText) {
                pieChart = new process_data.pieChart();
        PieChart chart1 = new PieChart();
        JLabel header = new JLabel(headerText);
        header.putClientProperty(FlatClientProperties.STYLE, "font:+1");
        chart1.setHeader(header);
        chart1.getChartColor().addColor(Color.decode("#f87171"), Color.decode("#fb923c"), Color.decode("#fbbf24"), Color.decode("#a3e635"), Color.decode("#34d399"), Color.decode("#22d3ee"), Color.decode("#818cf8"), Color.decode("#c084fc"));
        chart1.putClientProperty(FlatClientProperties.STYLE, "border:5,5,5,5,$Component.borderColor,,20");
        chart1.setDataset(pieChart.DataPieChart3());
        return chart1;
    }

    @SuppressWarnings("unchecked")
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
