/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel_Mau;

/**
 *
 * @author MY HP
 */
public class Menu extends javax.swing.JPanel {
    private Frame.HangHoa hh;
    private Frame.BacSi bs;
    private Frame.DoiTac dt;
    private Frame.DonHang dh;
    private Frame.KhachHang kh;
    private Frame.NhanVien nv;
    private Frame.ThuCung tc;
    private Frame.PhieuNhap nh;
    private Frame.Admin ad;
    private Frame.TONGQUAN tq;
    private Frame.LogIn lg;
    /**
     * Creates new form MeNu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jButton13.setBackground(new java.awt.Color(255, 79, 157));
        jButton13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-partner-25.png"))); // NOI18N
        jButton13.setText("Đối tác");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);

        jPanel3.setBackground(new java.awt.Color(255, 79, 157));
        jPanel3.setPreferredSize(new java.awt.Dimension(1600, 75));

        jButton18.setBackground(new java.awt.Color(255, 79, 157));
        jButton18.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-24.png"))); // NOI18N
        jButton18.setText("Tổng quan");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(255, 79, 157));
        jButton19.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-shop-24.png"))); // NOI18N
        jButton19.setText("Hàng hóa");
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);

        jButton20.setBackground(new java.awt.Color(255, 79, 157));
        jButton20.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-handshake-24.png"))); // NOI18N
        jButton20.setText("Giao dịch");
        jButton20.setBorder(null);
        jButton20.setBorderPainted(false);

        jButton21.setBackground(new java.awt.Color(255, 79, 157));
        jButton21.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-partner-25.png"))); // NOI18N
        jButton21.setText("Đối tác");
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);

        jButton22.setBackground(new java.awt.Color(255, 79, 157));
        jButton22.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-25.png"))); // NOI18N
        jButton22.setText("Nhân viên");
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);

        jButton23.setBackground(new java.awt.Color(255, 79, 157));
        jButton23.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-money-25.png"))); // NOI18N
        jButton23.setText("Sổ quỹ");
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);

        jButton24.setBackground(new java.awt.Color(255, 79, 157));
        jButton24.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-report-25.png"))); // NOI18N
        jButton24.setText("Báo cáo");
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(255, 79, 157));
        jButton25.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-customer-25.png"))); // NOI18N
        jButton25.setText("Khách hàng");
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 79, 157));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 75));

        jButton1.setBackground(new java.awt.Color(255, 79, 157));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-24.png"))); // NOI18N
        jButton1.setText("Tổng quan");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 79, 157));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-shop-24.png"))); // NOI18N
        jButton2.setText("Hàng hóa");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 79, 157));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-handshake-24.png"))); // NOI18N
        jButton3.setText("Đơn hàng");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 79, 157));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-doctor-25 (1).png"))); // NOI18N
        jButton4.setText("Bác sĩ");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 79, 157));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-25.png"))); // NOI18N
        jButton5.setText("Nhân viên");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(255, 79, 157));
        jButton14.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-customer-25.png"))); // NOI18N
        jButton14.setText("Khách hàng");
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(255, 79, 157));
        jButton26.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-partner-25.png"))); // NOI18N
        jButton26.setText("Đối tác");
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setBackground(new java.awt.Color(255, 79, 157));
        jButton27.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-cat-25.png"))); // NOI18N
        jButton27.setText("Thú cưng");
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 79, 157));
        jButton6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-money-25.png"))); // NOI18N
        jButton6.setText("Nhập hàng");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 79, 157));
        jButton7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-card-25.png"))); // NOI18N
        jButton7.setText("Admin");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 79, 157));
        jButton8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Thoát");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
            .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
        tq = new Frame.TONGQUAN();

        nv.setVisible(false);
        bs.setVisible(false);
        tc.setVisible(false);
        hh.setVisible(false);
        dh.setVisible(false);
        kh.setVisible(false);
        dt.setVisible(false);
        ad.setVisible(false);
        nh.setVisible(false);
        tq.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
        tq = new Frame.TONGQUAN();

        nv.setVisible(true);
        bs.setVisible(false);
        tc.setVisible(false);
        hh.setVisible(false);
        dh.setVisible(false);
        kh.setVisible(false);
        dt.setVisible(false);
        ad.setVisible(false);
        nh.setVisible(false);
        tq.setVisible(false);
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:        
         nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
        tq = new Frame.TONGQUAN();
      nv.setVisible(false);
        bs.setVisible(false);
        tc.setVisible(true);
        hh.setVisible(false);
        dh.setVisible(false);
        kh.setVisible(false);
        dt.setVisible(false);
        ad.setVisible(false);
        nh.setVisible(false);
        tq.setVisible(false);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
        tq = new Frame.TONGQUAN();
        nv.setVisible(false);
        bs.setVisible(false);
        tc.setVisible(false);
        hh.setVisible(false);
        dh.setVisible(false);
        kh.setVisible(false);
        dt.setVisible(false);
        ad.setVisible(false);
        nh.setVisible(true);
        tq.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
nh = new Frame.PhieuNhap();
        tq = new Frame.TONGQUAN();
         nv.setVisible(false);
        bs.setVisible(false);
        tc.setVisible(false);
        hh.setVisible(false);
        dh.setVisible(false);
        kh.setVisible(false);
        dt.setVisible(false);
        ad.setVisible(true);
        nh.setVisible(false);
        tq.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
nh = new Frame.PhieuNhap();
        tq = new Frame.TONGQUAN();
         nv.setVisible(false);
        bs.setVisible(false);
        tc.setVisible(false);
        hh.setVisible(true);
        dh.setVisible(false);
        kh.setVisible(false);
        dt.setVisible(false);
        ad.setVisible(false);
        nh.setVisible(false);
        tq.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
        tq = new Frame.TONGQUAN();
         nv.setVisible(false);
        bs.setVisible(false);
        tc.setVisible(false);
        hh.setVisible(false);
        dh.setVisible(true);
        kh.setVisible(false);
        dt.setVisible(false);
        ad.setVisible(false);
        nh.setVisible(false);
        tq.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
tq = new Frame.TONGQUAN();
        nv.setVisible(false);
        bs.setVisible(false);
        tc.setVisible(false);
        hh.setVisible(false);
        dh.setVisible(false);
        kh.setVisible(true);
        dt.setVisible(false);
        ad.setVisible(false);
        nh.setVisible(false);
        tq.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
     nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
tq = new Frame.TONGQUAN();
       nv.setVisible(false);
        bs.setVisible(false);
        tc.setVisible(false);
        hh.setVisible(false);
        dh.setVisible(false);
        kh.setVisible(false);
        dt.setVisible(true);
        ad.setVisible(false);
        nh.setVisible(false);
        tq.setVisible(false);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    nv = new Frame.NhanVien();
        tc = new Frame.ThuCung();
        hh = new Frame.HangHoa();
        dh = new Frame.DonHang();
        kh = new Frame.KhachHang();
        dt = new Frame.DoiTac();
        bs = new Frame.BacSi();
        ad = new Frame.Admin();
        nh = new Frame.PhieuNhap();
tq = new Frame.TONGQUAN();
       nv.setVisible(false);
        bs.setVisible(true);
        tc.setVisible(false);
        hh.setVisible(false);
        dh.setVisible(false);
        kh.setVisible(false);
        dt.setVisible(false);
        ad.setVisible(false);
        nh.setVisible(false);
        tq.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       lg = new Frame.LogIn();
       lg.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
